// Auto-generated by SoundLibraryExporter
namespace AudioSystem
{
    public static class SoundIDs
    {
        public static class BGM
        {
            public const string Lunaris = "BGM_Lunaris";
            public const string Sanctivar = "BGM_Sanctivar";
            public const string Abyss = "BGM_Abyss";
            public const string Boss = "BGM_Boss";
            public const string MainMenu = "BGM_MainMenu";
            public const string Safe = "BGM_Safe";
            public const string LightCombat = "BGM_LightCombat";
            public const string HeavyCombat = "BGM_HeavyCombat";
            public const string VictoryTheme = "BGM_VictoryTheme";
            public const string PhaseTransition = "BGM_PhaseTransition";
            public const string Cave_01 = "BGM_Cave_01";
            public const string Cave_02 = "BGM_Cave_02";



        }
        public static class AMB
        {
            public const string AbyssSurfaceRim = "AMB_Abyss_SurfaceRim";
            public const string AbyssDeepTunnels = "AMB_Abyss_DeepTunnels";
            public const string AbyssCoreHeartBeat = "AMB_Abyss_CoreHeartBeat";
            public const string LunarisPlazaDay = "AMB_Lunaris_PlazaDay";
            public const string LunarisOurskirts = "AMB_Lunaris_Outskirts";
            public const string SanctivarStreets = "AMB_Sanctivar_Streets";
            public const string SanctivarCathedralReactor = "AMB_Sanctivar_CathedralReactor";
            public const string SanctivarCathedralBells = "AMB_Sanctivar_CathedralReactor_Bells";
            public const string SanctivarCathedralChoir = "AMB_Sanctivar_CathedralReactor_Choir";

            public const string HollowPresence = "AMB_Hollow_Presence";
            public const string HollowChantLoop = "AMB_Hollow_ChantLoop";
            public const string Checkpoint = "AMB_Checkpoint";
            public const string Wind = "AMB_General_Wind";
            public const string Descent = "AMB_General_Descent";
            public const string TunnelPressureShift = "AMB_General_TunnelPressureShift";

            public const string ElevatorDescent = "AMB_General_ElevatorDescent";


        }
        public static class SFX
        {
            public static class Player
            {
                public const string Dash = "SFX_Player_Dash";
                public const string Run = "SFX_Player_Run";
                public const string Jump = "SFX_Player_Jump";
                public const string Hurt = "SFX_Player_Hurt";
                public const string Death = "SFX_Player_Death";
                public const string Land = "SFX_Player_Land";
            }

            public static class Spell
            {
                public const string ValidCast = "SFX_Spell_Cast";
                public const string InvalidCast = "SFX_Spell_InvalidCast";
                public const string Draw = "SFX_Spell_Draw";
                public const string ValidSpellstack = "SFX_Spell_ValidSpellStack";
                public const string InvalidSpellstack = "SFX_Spell_InvalidSpellStack";
                public const string Projectile = "SFX_Spell_Projectile";
                public const string AOE = "SFX_Spell_AOE";
                public const string BigAOE = "SFX_Spell_BigAOE";
                public const string Polymorph = "SFX_Spell_Polymorph";
                public const string ExplodingPolymorph = "SFX_Spell_ExplodingPolymorph";
                public const string Slow = "SFX_Spell_Slow";
                public const string ValidRuneDrawn = "SFX_Spell_ValidRuneDrawn";
                public const string InvalidRuneDrawn = "SFX_Spell_InvalidRuneDrawn";

            }


            public static class Enemy
            {
                public static class Boss
                {
                    public const string FanOfBolts = "SFX_Boss_FanOfBolts";
                    public const string TrapDelayExplosion = "SFX_Boss_TrapDelayExplosion";
                    public const string TrapDelayIndication = "SFX_Boss_TrapDelayIndication";
                    public const string CurseArea = "SFX_Boss_CurseArea";
                    public const string HoundingBolts = "SFX_Boss_HoundingBolts";
                    public const string SpawnMinion = "SFX_Boss_SpawnMinion";
                    public const string MajorCurseArea = "SFX_Boss_MajorCurseArea";
                    public const string StoneFall = "SFX_Boss_StoneFall";
                    public const string StoneImpact = "SFX_Boss_StoneImpact";
                    public const string RainFire = "SFX_RainFire";

                    public const string BulletHell = "SFX_Boss_BulletHell";
                    public const string Eruption = "SFX_Boss_Eruption";

                    public const string ExplodePolymorph = "SFX_Boss_ExplodePolymorph";

                    public const string Posession = "SFX_Boss_Posession";
                    public const string Miasma = "SFX_Boss_Miasma";
                    public const string Culling = "SFX_Boss_Culling";
                    public const string SummonPolymorph = "SFX_Boss_SummonPolymorph";



                }
                public const string Beam = "SFX_Enemy_ArcherBeam";
                public static class CagedShocker
                {
                    public const string Slash = "SFX_Enemy_CagedShockerSlash";
                    public const string Walk = "SFX_Enemy_CagedShockerWalk";

                }

                public static class BlindingSpider
                {
                    public const string Orb = "SFX_Enemy_SpiderOrb";
                    public const string Walk = "SFX_Enemy_SpiderWalk";

                }

                public static class Assassin
                {
                    public const string Slash = "SFX_Enemy_AssassinSlash";
                    public const string Walk = "SFX_Enemy_AssassinWalk";

                }


                public static class WheelBot
                {
                    public const string Idle = "SFX_Enemy_WheelBot_Idle";
                    public const string Walk = "SFX_Enemy_WheelBot_Walk";
                    public const string Fire = "SFX_Enemy_WheelBot_Fire";


                }
                public static class OrbMage
                {
                    public const string Wave = "SFX_Enemy_OrbMage_Wave";
                    public const string Spike = "SFX_Enemy_OrbMage_Spike";
                    public const string Shield = "SFX_Enemy_OrbMage_Shield";

                }
            }
            public static class Special
            {
                public const string Checkpoint = "SFX_Special_Checkpoint";
                public const string HealthPickUp = "SFX_Special_HealthPickUp";
                public const string FinalRock = "SFX_Special_FinalRock";
                public const string SmallRock = "SFX_Special_SmallRock";

            }

            public static class UI
            {
                public const string Click = "SFX_UI_Click";
                public const string Hover = "SFX_UI_Hover";

            }
        }
    }
}